apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: query-benchmark
  name: query-benchmark-${JOB_ID}
spec:
  ttlSecondsAfterFinished: 253800
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: query-benchmark-${JOB_ID}
        image: ${IMAGE_NAME}
        command: ["python", "-u", "benchmark.py", "--benchmark", "${BENCHMARK}"]
        volumeMounts:
          - name: sshkey
            mountPath: /ssh/
        resources:
          limits:
            memory: "4G"
      restartPolicy: Never
      volumes:
        - name: sshkey
          secret:
            secretName: sshkey
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ${NODE_NAME}
  backoffLimit: 0
