apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: query-benchmark
  name: query-benchmark-${JOB_ID}
spec:
  ttlSecondsAfterFinished: 253800
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: query-benchmark-${JOB_ID}
        image: ${IMAGE_NAME}
        command: ["python", "-u", "benchmark.py", "--benchmark", "${BENCHMARK}"]
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ais-etl-worker
  backoffLimit: 0
