apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: load-etl
  name: load-etl-${JOB_ID}
spec:
  ttlSecondsAfterFinished: 253800
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: load-etl-${JOB_ID}
        image: ${IMAGE_NAME}
        command: ["./main_wrapper.sh", "--load", "--from_date", "${FROM_DATE}", "--to_date", "${TO_DATE}"]
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ${NODE_NAME}
  backoffLimit: 0
