apiVersion: batch/v1
kind: Job
metadata:
  name: query-benchmark-${JOB_ID}
spec:
  ttlSecondsAfterFinished: 253800
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: query-benchmark-${JOB_ID}
        image: ${IMAGE_NAME}
        command: ["python", "-u", "main.py", "--querybenchmark"]
        volumeMounts:
          - name: sshkey
            mountPath: /ssh/
      restartPolicy: Never
      volumes:
          - name: sshkey
            secret:
                secretName: sshkey
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ais-etl-worker
  backoffLimit: 0
